"""
Reporting functionality for KernelScope.
"""

import json
from datetime import datetime
from typing import Dict, Any, List
from pathlib import Path
from ..parsers.base_parser import LogEvent
from ..analyzers import DiagnosticSummary


class ReportGenerator:
    """Generates diagnostic reports in multiple formats."""

    def __init__(self, events: List[LogEvent], log_file: str = "unknown"):
        """
        Initialize report generator.

        Args:
            events: List of parsed log events
            log_file: Name of the log file
        """
        self.events = events
        self.log_file = log_file
        self.summary_gen = DiagnosticSummary(events)

    def generate_markdown(self) -> str:
        """
        Generate markdown report.

        Returns:
            Markdown formatted report
        """
        report = self.summary_gen.generate_detailed_report()

        md = f"""# KernelScope Diagnostic Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Log File:** {self.log_file}
**Total Events:** {len(self.events)}

---

## Executive Summary
{report['summary']}

---

## Severity Assessment
**Overall Severity:** `{report['severity'].upper()}`

---

## Panic Analysis
- **Panics Detected:** {report['panic_analysis']['panic_count']}
- **Panic Types:** {', '.join(report['panic_analysis']['panic_types'].keys())}

---

## Driver Analysis
- **Total Failures:** {report['driver_analysis']['total_failures']}
- **Most Common Failure:** `{report['driver_analysis']['most_common_failure']}`
- **Affected Drivers:** {', '.join(report['driver_analysis']['affected_drivers'][:10])}

---

## Event Statistics
- **Total Events:** {report['event_statistics']['total_events']}
- **Error Events:** {report['event_statistics']['level_distribution'].get('error', 0)}
- **Warning Events:** {report['event_statistics']['level_distribution'].get('warning', 0)}
- **Info Events:** {report['event_statistics']['level_distribution'].get('info', 0)}

**Subsystem Distribution:**
"""

        for subsystem, count in sorted(
            report['event_statistics']['subsystem_distribution'].items(),
            key=lambda x: x[1],
            reverse=True
        )[:10]:
            md += f"- {subsystem}: {count} events\n"

        md += "\n---\n\n## Recommendations\n\n"
        for rec in report['recommendations']:
            md += f"{rec}\n"

        md += "\n---\n\n*Generated by KernelScope - Linux & Android Diagnostics Dashboard*"

        return md

    def generate_json(self) -> str:
        """
        Generate JSON report.

        Returns:
            JSON formatted report
        """
        report = self.summary_gen.generate_detailed_report()

        json_report = {
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "log_file": self.log_file,
                "total_events": len(self.events),
                "generator": "KernelScope v1.0.0"
            },
            "analysis": report
        }

        return json.dumps(json_report, indent=2)

    def generate_html(self) -> str:
        """
        Generate HTML report.

        Returns:
            HTML formatted report
        """
        report = self.summary_gen.generate_detailed_report()

        severity_colors = {
            "low": "#10B981",
            "medium": "#F59E0B",
            "high": "#EF4444",
            "critical": "#7C3AED"
        }

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KernelScope Diagnostic Report</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #0f0f0f;
            color: #e5e5e5;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }}
        h1 {{
            color: #3B82F6;
            border-bottom: 2px solid #3B82F6;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #60A5FA;
            margin-top: 30px;
        }}
        .metadata {{
            background-color: #1a1a1a;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
        }}
        .severity {{
            display: inline-block;
            padding: 10px 20px;
            border-radius: 5px;
            font-weight: bold;
            color: white;
            background-color: {severity_colors.get(report['severity'], '#6B7280')};
        }}
        .section {{
            background-color: #1a1a1a;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }}
        .stat-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }}
        .stat {{
            background-color: #2a2a2a;
            padding: 15px;
            border-radius: 5px;
            text-align: center;
        }}
        .stat-value {{
            font-size: 24px;
            font-weight: bold;
            color: #3B82F6;
        }}
        .recommendation {{
            background-color: #2a2a2a;
            padding: 10px 15px;
            margin: 5px 0;
            border-left: 4px solid #3B82F6;
            border-radius: 3px;
        }}
        ul {{
            list-style-type: none;
            padding: 0;
        }}
    </style>
</head>
<body>
    <h1>🔧 KernelScope Diagnostic Report</h1>

    <div class="metadata">
        <p><strong>Generated:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        <p><strong>Log File:</strong> {self.log_file}</p>
        <p><strong>Total Events:</strong> {len(self.events)}</p>
    </div>

    <div class="section">
        <h2>Executive Summary</h2>
        <p>{report['summary']}</p>
        <p style="margin-top: 20px;">
            <strong>Overall Severity:</strong>
            <span class="severity">{report['severity'].upper()}</span>
        </p>
    </div>

    <div class="section">
        <h2>Panic Analysis</h2>
        <div class="stat-grid">
            <div class="stat">
                <div class="stat-value">{report['panic_analysis']['panic_count']}</div>
                <div>Panics Detected</div>
            </div>
            <div class="stat">
                <div class="stat-value">{len(report['panic_analysis']['panic_types'])}</div>
                <div>Panic Types</div>
            </div>
        </div>
        <p><strong>Panic Types:</strong> {', '.join(report['panic_analysis']['panic_types'].keys())}</p>
    </div>

    <div class="section">
        <h2>Driver Analysis</h2>
        <div class="stat-grid">
            <div class="stat">
                <div class="stat-value">{report['driver_analysis']['total_failures']}</div>
                <div>Total Failures</div>
            </div>
            <div class="stat">
                <div class="stat-value">{report['driver_analysis']['most_common_failure']}</div>
                <div>Most Common Failure</div>
            </div>
        </div>
        <p><strong>Affected Drivers:</strong> {', '.join(report['driver_analysis']['affected_drivers'][:10])}</p>
    </div>

    <div class="section">
        <h2>Event Statistics</h2>
        <div class="stat-grid">
            <div class="stat">
                <div class="stat-value">{report['event_statistics']['total_events']}</div>
                <div>Total Events</div>
            </div>
            <div class="stat">
                <div class="stat-value">{report['event_statistics']['level_distribution'].get('error', 0)}</div>
                <div>Errors</div>
            </div>
            <div class="stat">
                <div class="stat-value">{report['event_statistics']['level_distribution'].get('warning', 0)}</div>
                <div>Warnings</div>
            </div>
            <div class="stat">
                <div class="stat-value">{report['event_statistics']['level_distribution'].get('info', 0)}</div>
                <div>Info</div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Recommendations</h2>
        <ul>
"""

        for rec in report['recommendations']:
            html += f'            <li class="recommendation">{rec}</li>\n'

        html += """        </ul>
    </div>

    <footer style="text-align: center; margin-top: 40px; color: #6B7280;">
        <p>Generated by KernelScope - Linux & Android Diagnostics Dashboard</p>
    </footer>
</body>
</html>"""

        return html

    def save_report(self, format: str, output_path: str) -> None:
        """
        Save report to file.

        Args:
            format: Output format (markdown, json, html)
            output_path: Output file path
        """
        if format == "markdown":
            content = self.generate_markdown()
            if not output_path.endswith(".md"):
                output_path += ".md"
        elif format == "json":
            content = self.generate_json()
            if not output_path.endswith(".json"):
                output_path += ".json"
        elif format == "html":
            content = self.generate_html()
            if not output_path.endswith(".html"):
                output_path += ".html"
        else:
            raise ValueError(f"Unsupported format: {format}")

        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

"""
Report generator module for creating diagnostic reports in markdown, JSON, and HTML formats.
"""
